version: 1.0.{build}

branches:
  only:
  - master
  - devel

clone_folder: c:\dev\icub-hri

environment:
  ACE_ROOT:          c:/Program Files (x86)/robotology/ace-6.5.0_v14_x86
  GSL_DIR:           c:/Program Files (x86)/robotology/gsl-1.14
  IPOPT_DIR:         c:/Program Files (x86)/robotology/ipopt-3.12.7
  OpenCV_DIR:        c:/Program Files (x86)/robotology/opencv-3.4.2-v14-x86
  Qt5_DIR:           c:/Program Files (x86)/robotology/Qt-5.11.1_v14_x86
  YARP_DIR:          c:/Program Files (x86)/robotology/yarp-3.1.0
  ICUB_DIR:          c:/Program Files (x86)/robotology/icub-1.12.0
  ICUBcontrib_DIR:   c:/iCubContrib
  CMAKE_PREFIX_PATH: c:/iCubContrib

install:
  - cmd: appveyor DownloadFile "https://github.com/robotology/yarp/releases/download/v3.1.0/yarp_3.1.0_v14_x86_1.exe" -FileName "c:\dev\yarp.exe"
  - cmd: appveyor DownloadFile "https://github.com/robotology/icub-main/releases/download/v1.12.0/iCub_1.12.0_v14_x86_1.exe" -FileName "c:\dev\icub.exe"

  - cmd: start "" /WAIT "c:\dev\yarp.exe" /S
  - cmd: timeout 10
  - cmd: start "" /WAIT "c:\dev\icub.exe" /S
  - cmd: timeout 10
  - cmd: dir "c:\Program Files (x86)\robotology"
  - cmd: dir "c:\Program Files (x86)\robotology\opencv-3.4.2-v14-x86"
  - cmd: type "c:\Program Files (x86)\robotology\opencv-3.4.2-v14-x86\OpenCVConfig.cmake"
  - cmd: pip install patch
  - cmd: python -m patch -d "c:\Program Files (x86)\robotology\opencv-3.4.2-v14-x86\" "c:\dev\icub-hri\conf\fix_opencv_cmake.patch"
  
  - cmd: git clone https://github.com/robotology/icub-contrib-common.git c:\dev\icub-contrib-common
  - cmd: cd c:\dev\icub-contrib-common
  - cmd: md build
  - cmd: cd build
  - cmd: cmake -DCMAKE_INSTALL_PREFIX=c:/iCubContrib -G"Visual Studio 14" ..
  - cmd: msbuild /m /p:Configuration=Release /p:Platform="Win32" INSTALL.vcxproj

  - cmd: git clone https://github.com/robotology/kinect-wrapper.git c:\dev\kinect-wrapper
  - cmd: cd c:\dev\kinect-wrapper
  - cmd: md build
  - cmd: cd build
  - cmd: cmake -G"Visual Studio 14" ..
  - cmd: msbuild /m /p:Configuration=Release /p:Platform="Win32" INSTALL.vcxproj

build:

build_script:
  - cd c:\dev\icub-hri\
  - md build
  - cd build
  - cmake -G"Visual Studio 14" -DICUBCLIENT_BUILD_IOL2OPC=FALSE -DCOMPILE_TESTS=TRUE ..
  - msbuild /m /p:Configuration=Release /p:Platform="Win32" icubclient.sln

notifications:
  - provider: Email
    to:
      - ugo.pattacini@iit.it
      - jordiysard@gmail.com
      - t.fischer@imperial.ac.uk
      - clement.moulinfrier@gmail.com
      - dcamilleri1@sheffield.ac.uk
      - Phuong.Nguyen@iit.it
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
