version: 1.0.{build}

platform:
- x64

branches:
  only:
  - master

clone_folder: c:\robotology\icub-hri

environment:
  ICUBcontrib_DIR:   c:/iCubContrib
  CMAKE_PREFIX_PATH: c:/iCubContrib

install:
  - cmd: dir "C:\Program Files (x86)\"
  - cmd: dir "C:\Program Files\"
  # - call "C:\Program Files (x86)\Microsoft Visual Studio 16.0\VC\vcvarsall.bat" x86_amd64

  - cmd: appveyor DownloadFile "https://github.com/robotology-playground/robotology-superbuild-dependencies/releases/download/v0.0.3/vcpkg-robotology.zip" -FileName "c:\robotology\vcpkg-robotology.zip"
  - cmd: cd c:\robotology
  - cmd: 7z x vcpkg-robotology.zip
  - cmd: dir c:\robotology

  # yarp
  - cmd: git clone https://github.com/robotology/yarp.git c:\robotology\yarp --depth 1 --branch master
  - cmd: cd c:\robotology\yarp
  - cmd: md build
  - cmd: cd build
  - cmd: cmake -G"Visual Studio 16 2019" ..
  - cmd: msbuild /m /p:Configuration=Release /p:Platform="x64" INSTALL.vcxproj
  
  # icub-main
  - cmd: git clone https://github.com/robotology/icub-main.git c:\robotology\icub-main --depth 1 --branch master
  - cmd: cd c:\robotology\icub-main
  - cmd: md build
  - cmd: cd build
  - cmd: cmake -G"Visual Studio 16 2019" ..
  - cmd: msbuild /m /p:Configuration=Release /p:Platform="x64" INSTALL.vcxproj

  # icub-contrib-common
  - cmd: git clone https://github.com/robotology/icub-contrib-common.git c:\robotology\icub-contrib-common --depth 1 --branch master
  - cmd: cd c:\robotology\icub-contrib-common
  - cmd: md build
  - cmd: cd build
  - cmd: cmake -DCMAKE_INSTALL_PREFIX=c:/iCubContrib -G"Visual Studio 16 2019" ..
  - cmd: msbuild /m /p:Configuration=Release /p:Platform="x64" INSTALL.vcxproj

  # kinect-wrapper
  - cmd: git clone https://github.com/robotology/kinect-wrapper.git c:\robotology\kinect-wrapper --depth 1 --branch master
  - cmd: cd c:\robotology\kinect-wrapper
  - cmd: md build
  - cmd: cd build
  - cmd: cmake -G"Visual Studio 16 2019" ..
  - cmd: msbuild /m /p:Configuration=Release /p:Platform="x64" INSTALL.vcxproj

build:

build_script:
  - cd c:\robotology\icub-hri\
  - md build
  - cd build
  - cmake -G"Visual Studio 16 2019" -DICUBCLIENT_COMPILE_TESTS=TRUE ..
  - msbuild /m /p:Configuration=Release /p:Platform="x64" icubclient.sln

notifications:
  - provider: Email
    to:
      # - ugo.pattacini@iit.it
      # - jordiysard@gmail.com
      - t.fischer@imperial.ac.uk
      # - clement.moulinfrier@gmail.com
      # - dcamilleri1@sheffield.ac.uk
      # - Phuong.Nguyen@iit.it
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
